library(bslib)
library(markdown)
library(shiny)
library(shinyWidgets)
library(tidyverse)

options(dplyr.summarise.inform=FALSE)

# LOCATIONS

locations <- read_csv(
  "data/locations.csv",
  col_types=cols(
    id="i",
    parent_id="i",
    name="c",
    name_indented="c",
    capacity="i",
    earliest_count="D",
    is_active="l"
  )
)

# The locations as read in are in depth-first hierarchical order.  We
# represent location names as an ordered factor both here and further
# below to ensure that that order is preserved.

locations <- locations %>%
  mutate(name=ordered(name, levels=locations$name))

# QUARTERS AND ACADEMIC YEARS

quarters <- read_csv(
  "data/quarters.csv",
  col_types=cols(
    name="c",
    start="D",
    end="D",
    start_prev_sunday="D",
    thanksgiving_week_num="i",
    academic_year="c"
  )
)

# Quarters as read in are in calendar order, which again, we want to
# preserve.

academic_years <- tibble(
  name=unique(quarters$academic_year) # preserves calendar order
)

academic_years <- academic_years %>%
  mutate(name=ordered(name, levels=academic_years$name))

quarters <- quarters %>%
  mutate(
    name=ordered(name, levels=quarters$name),
    academic_year=ordered(academic_year, levels=academic_years$name)
  )

# DATA

weekdays <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")

data <- read_csv(
    "data/data.csv",
    col_types=cols(
      location="c",
      timestamp="T",
      academic_year="c",
      quarter="c",
      quarter_week_num="i",
      weekday="c",
      hour="i",
      count="i",
      percentage="d"
    )
  ) %>%
  filter(percentage < 2) %>% # remove crazy large numbers
  select(-timestamp, -count) # remove unused columns

data <- data %>% mutate(
  location=ordered(location, levels=locations$name),
  academic_year=ordered(academic_year, levels=academic_years$name),
  quarter=ordered(quarter, levels=quarters$name),
  weekday=ordered(weekday, levels=weekdays)
)

# TIME PERIOD MENU

indentation <- "&nbsp;&nbsp;&nbsp;&nbsp;"

time_period_menu <- c()
time_period_menu_indented <- c()
relevant_quarters <- quarters %>%
  filter(between(name, min(data$quarter), max(data$quarter)))
academic_year <- -1
for (i in rownames(relevant_quarters)) {
  q <- relevant_quarters[i,]
  if (q$academic_year != academic_year) {
    academic_year <- q$academic_year
    time_period_menu <- append(time_period_menu, as.character(academic_year))
    time_period_menu_indented <- (
      append(time_period_menu_indented, as.character(academic_year))
    )
  }
  time_period_menu <- append(time_period_menu, as.character(q$name))
  time_period_menu_indented <- append(
    time_period_menu_indented,
    paste(indentation, as.character(q$name), sep="")
  )
}

# LINE COLOR PALETTE

# To make line color consistent as the user selects different items to
# plot, we assign each plotted item (each location, academic year, and
# quarter) a fixed color.  The following colors were generated by
# https://mokole.com/palette.html.

line_colors = c(
  "#FF8C00",
  "#FFFF00",
  "#00FF00",
  "#00FFFF",
  "#FF00FF",
  "#1E90FF",
  "#EEE8AA",
  "#FF69B4",
  "#2F4F4F",
  "#7F0000",
  "#008000",
  "#000080"
)

locations <- rowid_to_column(locations) %>%
  mutate(color=line_colors[((rowid-1) %% length(line_colors)) + 1]) %>%
  select(-rowid)

academic_years <- rowid_to_column(academic_years) %>%
  mutate(color=line_colors[((rowid-1) %% length(line_colors)) + 1]) %>%
  select(-rowid)

quarters <- rowid_to_column(quarters) %>%
  mutate(color=line_colors[((rowid-1) %% length(line_colors)) + 1]) %>%
  select(-rowid)
